export interface CountryCode {
  name: string;
  flag: string;
  code: string;
  digits: number;
}

export const COUNTRY_CODES: CountryCode[] = [
  // Primary / Frequently used
  { name: "India", flag: "🇮🇳", code: "+91", digits: 10 },
  { name: "United States", flag: "🇺🇸", code: "+1", digits: 10 },
  { name: "United Kingdom", flag: "🇬🇧", code: "+44", digits: 10 },
  { name: "Canada", flag: "🇨🇦", code: "+1", digits: 10 },
  { name: "Australia", flag: "🇦🇺", code: "+61", digits: 9 },
  { name: "UAE", flag: "🇦🇪", code: "+971", digits: 9 },
  { name: "Saudi Arabia", flag: "🇸🇦", code: "+966", digits: 9 },
  { name: "Singapore", flag: "🇸🇬", code: "+65", digits: 8 },
  { name: "Malaysia", flag: "🇲🇾", code: "+60", digits: 9 },
  { name: "Germany", flag: "🇩🇪", code: "+49", digits: 10 },
  { name: "France", flag: "🇫🇷", code: "+33", digits: 9 },

  // Asia & Middle East
  { name: "Afghanistan", flag: "🇦🇫", code: "+93", digits: 9 },
  { name: "Bahrain", flag: "🇧🇭", code: "+973", digits: 8 },
  { name: "Bangladesh", flag: "🇧🇩", code: "+880", digits: 10 },
  { name: "Bhutan", flag: "🇧🇹", code: "+975", digits: 8 },
  { name: "China", flag: "🇨🇳", code: "+86", digits: 11 },
  { name: "Hong Kong", flag: "🇭🇰", code: "+852", digits: 8 },
  { name: "Indonesia", flag: "🇮🇩", code: "+62", digits: 10 },
  { name: "Iran", flag: "🇮🇷", code: "+98", digits: 10 },
  { name: "Iraq", flag: "🇮🇶", code: "+964", digits: 10 },
  { name: "Israel", flag: "🇮🇱", code: "+972", digits: 9 },
  { name: "Japan", flag: "🇯🇵", code: "+81", digits: 10 },
  { name: "Jordan", flag: "🇯🇴", code: "+962", digits: 9 },
  { name: "Kazakhstan", flag: "🇰🇿", code: "+7", digits: 10 },
  { name: "Kuwait", flag: "🇰🇼", code: "+965", digits: 8 },
  { name: "Lebanon", flag: "🇱🇧", code: "+961", digits: 8 },
  { name: "Maldives", flag: "🇲🇻", code: "+960", digits: 7 },
  { name: "Myanmar", flag: "🇲🇲", code: "+95", digits: 9 },
  { name: "Nepal", flag: "🇳🇵", code: "+977", digits: 10 },
  { name: "Oman", flag: "🇴🇲", code: "+968", digits: 8 },
  { name: "Pakistan", flag: "🇵🇰", code: "+92", digits: 10 },
  { name: "Philippines", flag: "🇵🇭", code: "+63", digits: 10 },
  { name: "Qatar", flag: "🇶🇦", code: "+974", digits: 8 },
  { name: "South Korea", flag: "🇰🇷", code: "+82", digits: 10 },
  { name: "Sri Lanka", flag: "🇱🇰", code: "+94", digits: 9 },
  { name: "Taiwan", flag: "🇹🇼", code: "+886", digits: 9 },
  { name: "Thailand", flag: "🇹🇭", code: "+66", digits: 9 },
  { name: "Turkey", flag: "🇹🇷", code: "+90", digits: 10 },
  { name: "Uzbekistan", flag: "🇺🇿", code: "+998", digits: 9 },
  { name: "Vietnam", flag: "🇻🇳", code: "+84", digits: 9 },
  { name: "Yemen", flag: "🇾🇪", code: "+967", digits: 9 },

  // Europe
  { name: "Austria", flag: "🇦🇹", code: "+43", digits: 10 },
  { name: "Belgium", flag: "🇧🇪", code: "+32", digits: 9 },
  { name: "Bulgaria", flag: "🇧🇬", code: "+359", digits: 9 },
  { name: "Croatia", flag: "🇭🇷", code: "+385", digits: 9 },
  { name: "Cyprus", flag: "🇨🇾", code: "+357", digits: 8 },
  { name: "Czech Republic", flag: "🇨🇿", code: "+420", digits: 9 },
  { name: "Denmark", flag: "🇩🇰", code: "+45", digits: 8 },
  { name: "Finland", flag: "🇫🇮", code: "+358", digits: 9 },
  { name: "Greece", flag: "🇬🇷", code: "+30", digits: 10 },
  { name: "Hungary", flag: "🇭🇺", code: "+36", digits: 9 },
  { name: "Iceland", flag: "🇮🇸", code: "+354", digits: 7 },
  { name: "Ireland", flag: "🇮🇪", code: "+353", digits: 9 },
  { name: "Italy", flag: "🇮🇹", code: "+39", digits: 10 },
  { name: "Luxembourg", flag: "🇱🇺", code: "+352", digits: 9 },
  { name: "Netherlands", flag: "🇳🇱", code: "+31", digits: 9 },
  { name: "Norway", flag: "🇳🇴", code: "+47", digits: 8 },
  { name: "Poland", flag: "🇵🇱", code: "+48", digits: 9 },
  { name: "Portugal", flag: "🇵🇹", code: "+351", digits: 9 },
  { name: "Romania", flag: "🇷🇴", code: "+40", digits: 9 },
  { name: "Russia", flag: "🇷🇺", code: "+7", digits: 10 },
  { name: "Serbia", flag: "🇷🇸", code: "+381", digits: 9 },
  { name: "Slovakia", flag: "🇸🇰", code: "+421", digits: 9 },
  { name: "Spain", flag: "🇪🇸", code: "+34", digits: 9 },
  { name: "Sweden", flag: "🇸🇪", code: "+46", digits: 9 },
  { name: "Switzerland", flag: "🇨🇭", code: "+41", digits: 9 },
  { name: "Ukraine", flag: "🇺🇦", code: "+380", digits: 9 },

  // Americas
  { name: "Argentina", flag: "🇦🇷", code: "+54", digits: 10 },
  { name: "Brazil", flag: "🇧🇷", code: "+55", digits: 11 },
  { name: "Chile", flag: "🇨🇱", code: "+56", digits: 9 },
  { name: "Colombia", flag: "🇨🇴", code: "+57", digits: 10 },
  { name: "Costa Rica", flag: "🇨🇷", code: "+506", digits: 8 },
  { name: "Ecuador", flag: "🇪🇨", code: "+593", digits: 9 },
  { name: "Mexico", flag: "🇲🇽", code: "+52", digits: 10 },
  { name: "Panama", flag: "🇵🇦", code: "+507", digits: 8 },
  { name: "Peru", flag: "🇵🇪", code: "+51", digits: 9 },
  { name: "Uruguay", flag: "🇺🇾", code: "+598", digits: 8 },
  { name: "Venezuela", flag: "🇻🇪", code: "+58", digits: 10 },

  // Africa & Oceania
  { name: "Algeria", flag: "🇩🇿", code: "+213", digits: 9 },
  { name: "Egypt", flag: "🇪🇬", code: "+20", digits: 10 },
  { name: "Ethiopia", flag: "🇪🇹", code: "+251", digits: 9 },
  { name: "Ghana", flag: "🇬🇭", code: "+233", digits: 9 },
  { name: "Kenya", flag: "🇰🇪", code: "+254", digits: 9 },
  { name: "Morocco", flag: "🇲🇦", code: "+212", digits: 9 },
  { name: "New Zealand", flag: "🇳🇿", code: "+64", digits: 9 },
  { name: "Nigeria", flag: "🇳🇬", code: "+234", digits: 10 },
  { name: "South Africa", flag: "🇿🇦", code: "+27", digits: 9 },
  { name: "Tanzania", flag: "🇹🇿", code: "+255", digits: 9 },
  { name: "Uganda", flag: "🇺🇬", code: "+256", digits: 9 },
  { name: "Zimbabwe", flag: "🇿🇼", code: "+263", digits: 9 },
];
