import { mockUsers } from "./dev-mode";
import { ArtistProfile, Category } from "@/types/artist";

const mockGenres: Category[] = [
  { id: "g-1", name: "Pop", type: "genre", is_active: true, created_at: new Date().toISOString() },
  { id: "g-2", name: "Rock", type: "genre", is_active: true, created_at: new Date().toISOString() },
];

const mockLanguages: Category[] = [
  { id: "l-1", name: "English", type: "language", is_active: true, created_at: new Date().toISOString() },
  { id: "l-2", name: "Hindi", type: "language", is_active: true, created_at: new Date().toISOString() },
];

const defaultAvailability = {
  weekly_schedule: {
    Monday: { available: true, start: "09:00", end: "22:00" },
    Tuesday: { available: true, start: "09:00", end: "22:00" },
    Wednesday: { available: true, start: "09:00", end: "22:00" },
    Thursday: { available: true, start: "09:00", end: "22:00" },
    Friday: { available: true, start: "09:00", end: "23:00" },
    Saturday: { available: true, start: "10:00", end: "23:59" },
    Sunday: { available: true, start: "10:00", end: "22:00" },
  },
  break_time: { start: "14:00", end: "15:00" },
  holidays: [],
  blocked_dates: [],
};

export const mockPublicArtists: ArtistProfile[] = [
  {
    id: "ar-1",
    user_id: mockUsers.artist.id,
    user: mockUsers.artist,
    display_name: "Rhythm Collective",
    bio: "High-energy live band for corporate events, weddings, and music festivals.",
    genres: mockGenres,
    languages: mockLanguages,
    base_rate: 25000,
    rating: 4.8,
    verification_status: "approved",
    verification_notes: "Profile verified.",
    mobile_number: "9876543210",
    years_of_experience: 8,
    city: "Bangalore",
    state: "Karnataka",
    profile_image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    cover_image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
    band_type: "Band",
    total_members: 5,
    currency: "INR",
    travel_radius: 200,
    travel_charges: 2000,
    min_booking_hours: 2,
    max_booking_hours: 6,
    equipment: { sound_system: true, microphones: true },
    availability: defaultAvailability,
    documents: [],
    gallery: [{ url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4", is_cover: true, album: "Live" }],
    videos: [],
    youtube_links: [],
    instagram_reels: [],
    pricing_details: {},
    social_links: { instagram: "https://instagram.com/rhythmcollective" },
    achievements: ["Best Live Act 2025"],
    created_at: new Date().toISOString(),
  },
  {
    id: "ar-2",
    user_id: "usr-mock-2",
    user: { ...mockUsers.artist, id: "usr-mock-2", email: "aarav@live.com", full_name: "Aarav Sharma" },
    display_name: "Aarav Sharma Acoustic",
    bio: "Soulful acoustic guitar and vocals specializing in Bollywood unplugged.",
    genres: [mockGenres[0]],
    languages: mockLanguages,
    base_rate: 12000,
    rating: 4.9,
    verification_status: "approved",
    mobile_number: "9876543211",
    years_of_experience: 5,
    city: "Mumbai",
    state: "Maharashtra",
    profile_image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    cover_image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6",
    band_type: "Solo",
    total_members: 1,
    currency: "INR",
    travel_radius: 100,
    travel_charges: 1000,
    min_booking_hours: 1,
    max_booking_hours: 4,
    equipment: { guitar: true, mic: true },
    availability: defaultAvailability,
    documents: [],
    gallery: [],
    videos: [],
    youtube_links: [],
    instagram_reels: [],
    pricing_details: {},
    social_links: {},
    achievements: [],
    created_at: new Date().toISOString(),
  },
];
